storageClass:
  enabled: false
  name: nfs-csi
  defaultClass: false
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  mountOptions: []
  parameters:
    server: nfs.example.com
    share: /exports/k8s
  allowVolumeExpansion: true
