apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.hecSecretName }}
  namespace: openshift-logging
  annotations:
    managed-by: argocd.argoproj.io
    # argocd.argoproj.io/sync-wave: "1"
    # "helm.sh/hook": ""
    "helm.sh/hook-weight": "1"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: "{{ .Values.secretStoreName }}"
  data:
    - secretKey: hecToken
      remoteRef:
        key: "secret/{{ .Values.hecSecretName }}"
  # dataFrom:
  #   - extract:
  #       key: "secret/{{ .Values.hecSecretName }}"
  #       property: hecToken
      # rewrite:
      #   - transform:
      #       template: hecToken
  target:
    name: {{ .Values.hecSecretName }}
    creationPolicy: "Owner"
    template:
      # Possible Values: "Opaque", "kubernetes.io/dockerconfigjson", "kubernetes.io/tls", "kubernetes.io/ssh-auth"
      type: Opaque
      data:
        hecToken:  "{{ `{{ .hecToken }}` }}"
