---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.pullSecretSecretName }}
  namespace: openshift-gitops
  annotations:
    managed-by: argocd.argoproj.io
    # argocd.argoproj.io/sync-wave: "0"
    # "helm.sh/hook": ""
    "helm.sh/hook-weight": "0"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: "{{ .Values.secretStoreName }}"
  data:
    - secretKey: pull_secret_json
      remoteRef:
        key: "secret/{{ .Values.pullSecretSecretName }}"
  target:
    name: {{ .Values.pullSecretSecretName }}
    creationPolicy: "Owner"
    template:
      # Possible Values: "Opaque", "kubernetes.io/dockerconfigjson", "kubernetes.io/tls", "kubernetes.io/ssh-auth"
      type: Opaque
      data:
        pull_secret_json: "{{ `{{ .pull_secret_json }}` }}"
