apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.registriesCertsConfigMap | lower }}
  namespace: openshift-config
  annotations:
    managed-by: argocd.argoproj.io
    # argocd.argoproj.io/sync-wave: "0"
    # "helm.sh/hook": ""
    "helm.sh/hook-weight": "0"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  # Interval of time the Secret will be synchronized from secret provider (ie: AWS, Azure, GCP)
  refreshInterval: 5m

  # Name of the SecretStore/ClusterSecretStore - Used for authn against secret provider
  secretStoreRef:
    kind: ClusterSecretStore
    name: "{{ .Values.secretStoreName  | lower }}"

  data:
  {{ range $secretItem := .Values.registriesTrustedCerts }}
    - secretKey: "{{ $secretItem.templateKey }}"
      remoteRef:
        key: "secret/{{ $secretItem.caSecretName }}"
  {{ end }}
  # Name of the Secret to be created
  target:
    name: {{ .Values.registriesCertsConfigMap  | lower }}
    creationPolicy: "Owner"
    template:
      # Possible Values: "Opaque", "kubernetes.io/dockerconfigjson", "kubernetes.io/tls", "kubernetes.io/ssh-auth"
      mergePolicy: Replace
      type: Opaque
      data:
      {{ range $secretItem := .Values.registriesTrustedCerts }}
        {{ $secretItem.registryHost }}: '{{ printf "{{ .%s }}" $secretItem.templateKey  }}'
      {{ end }}
