---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.storage.credentialsSecretName | lower }}
  namespace: {{ .Values.namespace }}
  annotations:
    managed-by: argocd.argoproj.io
    # argocd.argoproj.io/sync-wave: "3"
    # "helm.sh/hook": ""
    "helm.sh/hook-weight": "3"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.secretStoreName }}
  data:
    - secretKey: access_key_id
      remoteRef:
        key: {{ .Values.storage.accessKeyIdRemoteRef }}
    - secretKey: secret_access_key
      remoteRef:
        key: {{ .Values.storage.secretAccessKeyRemoteRef }}
  target:
    name: {{ .Values.storage.credentialsSecretName | lower }}
    creationPolicy: "Owner"
    template:
      type: Opaque
      data:
        {{ .Values.veleroSecretKeyFile }}: |
          [default]
          aws_access_key_id={{ `{{ .access_key_id }}` }}
          aws_secret_access_key={{ `{{ .secret_access_key }}` }}
