{{- if .Values.clusterSecretStore.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: "{{ .Values.clusterSecretStore.name | lower }}"
  annotations:
    managed-by: argocd.argoproj.io
    "helm.sh/hook-weight": "5"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
{{ toYaml .Values.clusterSecretStore.spec | indent 2 }}
{{- end }}
