{{- range .Values.projects }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ index . "name" }}
  namespace: {{ default "openshift-gitops" (index . "namespace") }}
spec:
  description: {{ index . "description" | quote }}
  sourceRepos:
{{- range (default (list "*") (index . "sourceRepos")) }}
    - {{ . | quote }}
{{- end }}
  destinations:
{{- range (default (list (dict "namespace" "*" "server" "https://kubernetes.default.svc")) (index . "destinations")) }}
    - namespace: {{ index . "namespace" | quote }}
      server: {{ index . "server" | quote }}
{{- end }}
{{- with (index . "sourceNamespaces") }}
  sourceNamespaces:
{{- range . }}
    - {{ . | quote }}
{{- end }}
{{- end }}
  clusterResourceWhitelist:
{{- range (default (list (dict "group" "*" "kind" "*")) (index . "clusterResourceWhitelist")) }}
    - group: {{ index . "group" | quote }}
      kind: {{ index . "kind" | quote }}
{{- end }}
{{- with (index . "clusterResourceBlacklist") }}
  clusterResourceBlacklist:
{{- range . }}
    - group: {{ index . "group" | quote }}
      kind: {{ index . "kind" | quote }}
{{- end }}
{{- end }}
{{- with (index . "namespaceResourceWhitelist") }}
  namespaceResourceWhitelist:
{{- range . }}
    - group: {{ index . "group" | quote }}
      kind: {{ index . "kind" | quote }}
{{- end }}
{{- end }}
{{- with (index . "namespaceResourceBlacklist") }}
  namespaceResourceBlacklist:
{{- range . }}
    - group: {{ index . "group" | quote }}
      kind: {{ index . "kind" | quote }}
{{- end }}
{{- end }}
{{- end }}
