{{- range .Values.serviceAccounts }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  annotations:
    managed-by: argocd.argoproj.io
    "helm.sh/hook-weight": "0"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
{{- with .annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .labels }}
  labels:
{{ toYaml . | indent 4 }}
{{- end }}
automountServiceAccountToken: {{ default true .automountServiceAccountToken }}
{{- end }}
